fail_on_violations: true

coffeescript:
  enabled: true
  config_file: .coffeescript-style.json

javascript:
  enabled: true
  config_file: .javascript-style.json
  ignore_file: .javascript_ignore

scss:
  enabled: true
  config_file: .scss-style.yml