language: node_js
node_js:
- 9.10.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
- export PATH="$HOME/.yarn/bin:$PATH"
- npm install gulp -g
before_deploy: echo 'ready?'
deploy:
  provider: heroku
  api_key:
    secure: PGXMpKXMpl5V5zElUuplOfeYbbEBqN+9v0EUVl+u6/nwLA7+7u8NUPiOlj0nicdL6Wc6xYZ9NeNrhvjYTtkQkbUP4Tv6kTvIbMFvkKTrNrZMmjPmsgx+c20gztpb/7br23ThcbRwVG3zzX3wbdZceIvCJqTTx+f8uM+zBTzYoYUYJsHrDYbg/DBr4hmd+sL2xE4PwxbsqtFZkEcaUvsYsfEEVXJJnmH+sOiISAd3KCqH+GsUhittVXjsuX06Z2l1oPibGRdQx2Nobet59rbEHdYDx+NNNUDXUCRmGjipANzenH6R91+KXdT/1ZsX0hST7ZzFQv0JQniFyd0f+dxrYZFeXcGiwb6DiNYk2eA+2VI6yGYf20Yn6RdDEnY/yWZlsb8aIHbQBLWOapKHDX6AcoWwVwKRrDGdFQJqNEILlrID1oyvZD8qKtR7NSjXd8sMgB7U3LiBgIL/GcjYJIawXW3LFEbD4Rlz1lFFBt/9fp8frJGB3KsrGSPiQH8cKO0ycYRZFY0BQboMsIJDmk3SN91qwX2G+1ByKXTtGvGtl9XE1U54k4VrZzZ0GgbXJMgjZfmkd+q37EToh4rE2FinwdCTImJb/Ca++ry7vgphsgO2jnQqLOssLWp1FLpWcidh3hvAMXc3tDQDuh1ox+bg37ZdeFBbWaR7GUw+qX0cvxQ=
  skip_cleanup: true
  app: sugg-prod
  on: staging
cache:
  directories:
  - node_modules
