language: node_js
node_js:
- 9.10.0
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
- export PATH="$HOME/.yarn/bin:$PATH"
- npm install gulp -g
before_deploy: echo 'ready?'
deploy:
  provider: heroku
  api_key:
    secure: qEhhDikyaYPeHkEHF2wBxmIA5suBGWmlmC0vWoD7WxQ/xmAZaJyFul4L7Vw5urdFHok0YfWgmfaa1zczbA+qtCcmQf53Jw4c1Js2ufsXt5GfjcrzdPlrf7wFyed/tl6s3o15F0iZj9kJblwkQbwigDOHN9AICS0EHrwMpPddyIBnW3kfhHOq5KA85fKMZyjEe1DpKPWmnvnhGAiFtOrqVqPwYuJSJ+4so14csoI+wUmdK83pt3zvs6H0SacVzA2c/JCh/qoJ2zCCRb7FICXgQHcfZeIk3yWEcPZoRRmYV74q2aihyJ6boQhIB9GJI3mgK6cGdQ0rZUwqAt+4X+AoPlEM1viYjcxmum8v71MQQLYEzLyAjWCAZZQMym2FJqO+AHBw7ccQT01yI3e/cskt+BxogOtYqIdeBmYJ+eOy9VvVwf9NZrX/+quICKkp2iZKd+gwrGoBHR/KgYdv9HPpDGpy794gkWi9XRgkNZ9VhvZWdxzXa010D2i/rAk0T3dyc08xf15JVnaa6KZu0ZyjLbEk/oHaCOnRYoF0Ug2OOlaxDQj9xcoCTeQyU00af+4Pmv1DKjG9ekRiIsjOmS29dMg/sRYOKyUZlg5T7Lf+BdfmQXYTDGMTmrq1FBWvayj4iaHQLnpwjzEFhOKKqPgL5t3Q2DfeM6Z6X/yGERdVfsw=
  skip_cleanup: true
  app: sugg-prod
  on: staging
cache:
  directories:
  - node_modules
